apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: microservice-speaker-sample
  labels:
    app: microprofile-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: speaker-deployment
        app: speaker-deployment
        version: v1
    spec:
      containers:
      - name: microservice-speaker
        #change the image name
        image: registry.ng.bluemix.net/<namespace>/microservice-speaker
        ports:
          - containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: speaker-service
  labels:
    app: microprofile-app
spec:
  ports:
    - port: 9080
  selector:
    name: speaker-deployment
